import type { CSSProperties } from "react";

export const s = {
  card: (rejected: boolean): CSSProperties => ({
    border: "1px solid var(--border)",
    borderRadius: 9,
    background: "var(--bg-elevated)",
    padding: 16,
    opacity: rejected ? 0.56 : 1,
    transition: "opacity .15s, border-color .15s",
  }),
  topRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 11,
  } satisfies CSSProperties,
  confidence: { marginLeft: "auto" } satisfies CSSProperties,
  rule: {
    width: "100%",
    minHeight: 58,
    resize: "vertical",
    border: "1px solid var(--border)",
    borderRadius: 6,
    background: "var(--bg-surface)",
    color: "var(--text-primary)",
    fontSize: 14,
    fontWeight: 600,
    lineHeight: 1.5,
    padding: "7px 8px",
    margin: "0 0 10px",
  } satisfies CSSProperties,
  evidence: {
    border: "1px solid var(--border)",
    borderRadius: 7,
    overflow: "hidden",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  evidenceHeader: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    padding: "7px 10px",
    borderBottom: "1px solid var(--border)",
    color: "var(--text-muted)",
    fontSize: 12,
  } satisfies CSSProperties,
  evidenceLink: {
    display: "inline-flex",
    alignItems: "center",
    gap: 5,
    color: "var(--accent)",
    textDecoration: "none",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  snippet: {
    margin: 0,
    padding: "11px 12px",
    color: "var(--text-secondary)",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    lineHeight: 1.55,
    whiteSpace: "pre-wrap",
    overflowWrap: "anywhere",
  } satisfies CSSProperties,
  actions: {
    display: "flex",
    justifyContent: "flex-end",
    gap: 8,
    marginTop: 12,
  } satisfies CSSProperties,
} as const;
