import type { CSSProperties } from "react";

export const s = {
  body: { padding: 24 } satisfies CSSProperties,
  info: {
    display: "flex",
    alignItems: "flex-start",
    gap: 10,
    padding: "11px 13px",
    marginBottom: 20,
    border: "1px solid color-mix(in srgb, var(--accent) 35%, transparent)",
    borderRadius: 7,
    color: "var(--text-secondary)",
    background: "var(--accent-bg)",
    fontSize: 13,
    lineHeight: 1.5,
  } satisfies CSSProperties,
  infoIcon: { color: "var(--accent)", flexShrink: 0, marginTop: 1 } satisfies CSSProperties,
  split: {
    display: "flex",
    alignItems: "center",
    gap: 9,
    padding: "0 0 18px",
    color: "var(--text-secondary)",
    fontSize: 13,
    cursor: "pointer",
  } satisfies CSSProperties,
  splitCheckbox: { accentColor: "var(--accent)" } satisfies CSSProperties,
  draft: (multiple: boolean): CSSProperties => ({
    border: multiple ? "1px solid var(--border)" : "none",
    borderRadius: multiple ? 8 : 0,
    padding: multiple ? 16 : 0,
    marginBottom: multiple ? 14 : 0,
    background: multiple ? "var(--bg-surface)" : "transparent",
  }),
  draftHeading: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    fontWeight: 650,
    color: "var(--accent)",
    marginBottom: 16,
    textTransform: "uppercase",
    letterSpacing: "0.04em",
  } satisfies CSSProperties,
  fieldRow: {
    display: "grid",
    gridTemplateColumns: "minmax(0, 1fr) minmax(180px, .65fr)",
    gap: 16,
  } satisfies CSSProperties,
  enabled: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    minHeight: 42,
    padding: "0 12px",
    border: "1px solid var(--border-strong)",
    borderRadius: 7,
    color: "var(--text-secondary)",
    fontSize: 13,
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  bodyEditor: {
    border: "1px solid var(--border-strong)",
    borderRadius: 7,
    overflow: "hidden",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  bodyEditorHeader: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "8px 12px",
    borderBottom: "1px solid var(--border)",
    background: "var(--bg-surface)",
    fontSize: 12,
  } satisfies CSSProperties,
  filename: {
    fontFamily: "var(--font-mono, monospace)",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  tokens: { marginLeft: "auto", color: "var(--text-muted)" } satisfies CSSProperties,
  textarea: {
    display: "block",
    width: "100%",
    resize: "vertical",
    minHeight: 210,
    padding: "12px 14px",
    border: "none",
    outline: "none",
    background: "transparent",
    color: "var(--text-primary)",
    fontSize: 13,
    lineHeight: 1.6,
    fontFamily: "var(--font-mono, monospace)",
  } satisfies CSSProperties,
  loading: {
    padding: "40px 0",
    color: "var(--text-muted)",
    fontSize: 13,
    textAlign: "center",
  } satisfies CSSProperties,
  error: {
    color: "var(--crit)",
    background: "var(--crit-bg)",
    borderRadius: 7,
    padding: "9px 12px",
    fontSize: 13,
    marginBottom: 14,
  } satisfies CSSProperties,
  footer: {
    display: "flex",
    alignItems: "center",
    gap: 16,
    justifyContent: "space-between",
  } satisfies CSSProperties,
  footerHint: { color: "var(--text-muted)", fontSize: 12.5 } satisfies CSSProperties,
  footerActions: { display: "flex", gap: 10 } satisfies CSSProperties,
} as const;
